### ISSUE TITLE
config.h.in file does not exit

### ISSUE THREAD

**Issue by YoungRainy** [shishenghuang/MyG2O#1]
When executing the command "cmake ..", the following error occurs.

CMake Error: File /home/user/work/myBA/planeBA_myG2o/thirdParty/MyG2O-master/config.h.in does not exist.
CMake Error at CMakeLists.txt:79 (configure_file):
  configure_file Problem configuring file

**Comment by shishenghuang** [comment]
We have fix this bug, thank you!
